// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AccoutDetailModuleLessNamespace {
  export interface IAccoutDetailModuleLess {
    box: string
    container: string
    network: string
  }
}

declare const AccoutDetailModuleLessModule: AccoutDetailModuleLessNamespace.IAccoutDetailModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AccoutDetailModuleLessNamespace.IAccoutDetailModuleLess
}

export = AccoutDetailModuleLessModule
