// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ConnectFlaskModuleLessNamespace {
  export interface IConnectFlaskModuleLess {
    box: string
    container: string
  }
}

declare const ConnectFlaskModuleLessModule: ConnectFlaskModuleLessNamespace.IConnectFlaskModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ConnectFlaskModuleLessNamespace.IConnectFlaskModuleLess
}

export = ConnectFlaskModuleLessModule
