// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TransactionModuleLessNamespace {
  export interface ITransactionModuleLess {
    box: string
    container: string
    txForm: string
  }
}

declare const TransactionModuleLessModule: TransactionModuleLessNamespace.ITransactionModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TransactionModuleLessNamespace.ITransactionModuleLess
}

export = TransactionModuleLessModule
