// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TxRecordsModuleLessNamespace {
  export interface ITxRecordsModuleLess {
    box: string
    container: string
  }
}

declare const TxRecordsModuleLessModule: TxRecordsModuleLessNamespace.ITxRecordsModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TxRecordsModuleLessNamespace.ITxRecordsModuleLess
}

export = TxRecordsModuleLessModule
